//CLASS #3

// var a=10,b=20,c=30,d=40,e=50
// document.write(`<select>
//     <option value="">${a}</option>
//     <option value="">${b}</option>
//     <option value="">${c}</option>
//     <option value="">${d}</option>
//     <option value="">${e}</option>
// </select>`)

//()=parenthesis

//IF Statment

//City selection
//  var city=prompt("Enter your city name")       

//if(city==="karachi"){
//     alert("welcome to karachi")}
// else if(city==="lahore"){
//     alert("You lived in Lahore")}


//CNIC PROGRAM
// var age=+prompt("Enter your age")
   
// if(age>=18){
//     alert("You are eligible for CNIC")}
// else{
//     alert("You are not eligible for CNIC")}


// Percentage
// var percentage= +prompt("Enter your Percentage")

// if(percentage <40){
//     console.log("Your grade is F")
// }
// else if(percentage <=50){
//     console.log("Your garde is D")
// }
// else if(percentage <=60){
//       console.log("Tour garde is C")
// }
// else if(percentage <70){
//     console.log("Your grade is B")
// }
// else if(percentage <79){
//     console.log("Your grade is A")
// }
// else if(percentage<100){
//     console.log("Your grade is A+")
// }
// else{
//     console.log("Invalid Percentage")
// }
